{% set python_min = "3.10" %}
{% set name = "cyfi" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57ee49ca13572d77ab0bd1800dd0b79bb6e79add2a8a0fcff6fadb88598ebdd7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cyfi=cyfi.cli:app

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - bottleneck
    - cloudpathlib-s3 >=0.4.1
    - dask
    - geopandas
    - geopy
    - gitpython
    - gradio >=5.0
    - lightgbm
    - loguru
    - matplotlib-base
    - netCDF4
    - numpy
    - odc-stac
    - opencv
    - pandas
    - planetary-computer
    - platformdirs
    - plotly
    - pydantic >=2.0
    - pystac
    - pystac-client
    - python >={{ python_min }}
    - scikit-learn >=1.4
    - seaborn
    - repro-zipfile
    - rioxarray
    - tqdm
    - typer
    - xarray

test:
  imports:
    - cyfi
  commands:
    - pip check
    - cyfi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drivendataorg/cyfi
  summary: Estimate cyanobacteria density in small, inland water bodies using Sentinel-2 satellite imagery.
  license: MIT
  license_file: LICENSE
  description: |
    CyFi uses Sentinel-2 satellite imagery and machine learning to estimate cyanobacteria levels in small,
    inland water bodies in the U.S. CyFi can help water quality managers protect the public by flagging the
    highest-risk areas in lakes, reservoirs, and rivers quickly and easily.
  doc_url: https://cyfi.drivendata.org/
  dev_url: https://github.com/drivendataorg/cyfi

extra:
  recipe-maintainers:
    - ejm714
